#include <stdint.h>
#include <stdio.h>
#include "jit.h"
#define CHECK(x) do { if (!(x)) { fprintf(stderr,"check failed: %s:%d: %s\n",__FILE__,__LINE__,#x); return 1; } } while (0)
static int emit_add(TurboJSIRFunction *f){uint16_t a,b,r;TurboJS_IRFunctionInit(f,2);a=TurboJS_IRAllocateRegister(f);b=TurboJS_IRAllocateRegister(f);r=TurboJS_IRAllocateRegister(f);return r!=TURBOJS_IR_NO_REGISTER&&TurboJS_IREmit(f,(TurboJSIRInstruction){TURBOJS_IR_ARGUMENT,a,0,0,0,0,0})==TURBOJS_IR_OK&&TurboJS_IREmit(f,(TurboJSIRInstruction){TURBOJS_IR_ARGUMENT,b,0,0,1,0,0})==TURBOJS_IR_OK&&TurboJS_IREmit(f,(TurboJSIRInstruction){TURBOJS_IR_ADD_I64,r,a,b,0,0,1})==TURBOJS_IR_OK&&TurboJS_IREmit(f,(TurboJSIRInstruction){TURBOJS_IR_RETURN_I64,0,r,0,0,0,2})==TURBOJS_IR_OK;}
int main(void){
 TurboJSCodeCache*cache=TurboJS_CodeCacheCreate(8,1u<<20);TurboJSIRFunction callee,caller;TurboJSIRDiagnostic d;const TurboJSNativeFunction *cn=0,*rn=0;TurboJSNativeEntryHandle h;TurboJSClutchCallSite*site;uint16_t a,b,r;int ck=1,rk=2;int64_t args[2]={19,23},out=0;
 CHECK(cache&&emit_add(&callee));CHECK(TurboJS_CodeCacheCompile(cache,&ck,&callee,&cn,&d)==TURBOJS_IR_OK);TurboJS_NativeEntryHandleInit(&h);CHECK(TurboJS_CodeCacheAttachEntryHandle(cache,&ck,&h,TURBOJS_NATIVE_ENTRY_INT32,2)==TURBOJS_IR_OK);
 TurboJS_IRFunctionInit(&caller,2);a=TurboJS_IRAllocateRegister(&caller);b=TurboJS_IRAllocateRegister(&caller);r=TurboJS_IRAllocateRegister(&caller);site=TurboJS_IRAllocateClutchCallSite(&caller);CHECK(site&&r!=TURBOJS_IR_NO_REGISTER);TurboJS_ClutchCallSiteInit(site,&h,h.generation,TURBOJS_NATIVE_ENTRY_INT32,2);CHECK(TurboJS_ClutchCallSiteSetArgument(site,0,a)==TURBOJS_IR_OK);CHECK(TurboJS_ClutchCallSiteSetArgument(site,1,b)==TURBOJS_IR_OK);CHECK(TurboJS_IREmit(&caller,(TurboJSIRInstruction){TURBOJS_IR_ARGUMENT,a,0,0,0,0,0})==TURBOJS_IR_OK);CHECK(TurboJS_IREmit(&caller,(TurboJSIRInstruction){TURBOJS_IR_ARGUMENT,b,0,0,1,0,0})==TURBOJS_IR_OK);CHECK(TurboJS_IREmit(&caller,(TurboJSIRInstruction){TURBOJS_IR_CALL_NATIVE_I64,r,a,b,(int64_t)(uintptr_t)site,0,2})==TURBOJS_IR_OK);CHECK(TurboJS_IREmit(&caller,(TurboJSIRInstruction){TURBOJS_IR_RETURN_I64,0,r,0,0,0,3})==TURBOJS_IR_OK);CHECK(TurboJS_CodeCacheCompile(cache,&rk,&caller,&rn,&d)==TURBOJS_IR_OK);TurboJS_IRFunctionDestroy(&caller);TurboJS_IRFunctionDestroy(&callee);
 CHECK(TurboJS_NativeInvoke(rn,args,2,&out)==TURBOJS_IR_OK&&out==42);TurboJS_CodeCacheInvalidate(cache,&ck);CHECK(TurboJS_CodeCacheGetStats(cache).dependent_call_sites_invalidated==1);CHECK(TurboJS_NativeInvoke(rn,args,2,&out)==TURBOJS_IR_BAILOUT);TurboJS_CodeCacheDestroy(cache);puts("TurboJS Clutch dependency invalidation passed");return 0;}
