#include "jit.h"
#include <stdio.h>
#include <string.h>

#define CHECK(x) do{if(!(x)){fprintf(stderr,"check failed: %s:%d: %s\n",__FILE__,__LINE__,#x);return 1;}}while(0)
static int make_add(TurboJSIRFunction*f,int64_t c){uint16_t a,k,r;TurboJSIRInstruction in;TurboJS_IRFunctionInit(f,1);a=TurboJS_IRAllocateRegister(f);k=TurboJS_IRAllocateRegister(f);r=TurboJS_IRAllocateRegister(f);memset(&in,0,sizeof(in));in.opcode=TURBOJS_IR_ARGUMENT;in.destination=a;in.immediate=0;CHECK(TurboJS_IREmit(f,in)==TURBOJS_IR_OK);in.opcode=TURBOJS_IR_CONSTANT_I64;in.destination=k;in.immediate=c;CHECK(TurboJS_IREmit(f,in)==TURBOJS_IR_OK);in.opcode=TURBOJS_IR_ADD_I64;in.destination=r;in.left=a;in.right=k;CHECK(TurboJS_IREmit(f,in)==TURBOJS_IR_OK);in.opcode=TURBOJS_IR_RETURN_I64;in.left=r;CHECK(TurboJS_IREmit(f,in)==TURBOJS_IR_OK);return 0;}
int main(void){TurboJSIRFunction add1,add10;TurboJSFeedbackVector fb;TurboJSOptimizedFunction*opt=NULL;TurboJSOptimizingStats stats;TurboJSIRDiagnostic d;int64_t arg=41,result=0;TurboJSAOTModuleFunction fs[2];TurboJSAOTBuffer image={0};TurboJSAOTModule module={0};const TurboJSAOTLoadedFunction*loaded;TurboJSNativeFunction*native=NULL;
 CHECK(make_add(&add1,1)==0);CHECK(make_add(&add10,10)==0);TurboJS_FeedbackVectorInit(&fb,1);for(int i=0;i<1200;i++){int64_t x=i;TurboJS_FeedbackObserveCall(&fb,&x,1);TurboJS_FeedbackObserveResult(&fb,x+1);}CHECK(TurboJS_OptimizingCompile(&add1,&fb,&opt,&stats,&d)==TURBOJS_IR_OK);CHECK(stats.ssa.guards_inserted==1);CHECK(stats.allocated_intervals>0);CHECK(TurboJS_OptimizedAllocation(opt)!=NULL);CHECK(stats.native_code_bytes>0);CHECK(TurboJS_OptimizedInvoke(opt,&arg,1,&result)==TURBOJS_IR_OK);CHECK(result==42);
 fs[0].name="add1";fs[0].ir=&add1;fs[1].name="add10";fs[1].ir=&add10;CHECK(TurboJS_AOTSerializeModule(fs,2,&image,&d)==TURBOJS_IR_OK);CHECK(image.size>64);CHECK(TurboJS_AOTDeserializeModule(image.data,image.size,&module,&d)==TURBOJS_IR_OK);CHECK(module.function_count==2);loaded=TurboJS_AOTFindFunction(&module,"add10");CHECK(loaded!=NULL);CHECK(TurboJS_BaselineCompile(&loaded->ir,&native,&d)==TURBOJS_IR_OK);CHECK(TurboJS_NativeInvoke(native,&arg,1,&result)==TURBOJS_IR_OK);CHECK(result==51);image.data[image.size-1]^=1;{TurboJSAOTModule corrupt={0};CHECK(TurboJS_AOTDeserializeModule(image.data,image.size,&corrupt,&d)!=TURBOJS_IR_OK);}printf("optimizing execution and multi-function AOT module passed\n");TurboJS_NativeFunctionDestroy(native);TurboJS_AOTModuleDestroy(&module);TurboJS_AOTBufferDestroy(&image);TurboJS_OptimizedFunctionDestroy(opt);TurboJS_IRFunctionDestroy(&add1);TurboJS_IRFunctionDestroy(&add10);return 0;}
