#ifndef TURBOJS_INTERNAL_SUBSYSTEM_H
#define TURBOJS_INTERNAL_SUBSYSTEM_H

/* Stable numeric identifiers used by diagnostics and architecture tooling. */
typedef enum QJSInternalSubsystem {
    TURBOJS_SUBSYSTEM_CORE = 1,
    TURBOJS_SUBSYSTEM_RUNTIME,
    TURBOJS_SUBSYSTEM_OBJECTS,
    TURBOJS_SUBSYSTEM_GC,
    TURBOJS_SUBSYSTEM_VM,
    TURBOJS_SUBSYSTEM_COMPILER,
    TURBOJS_SUBSYSTEM_MODULES,
    TURBOJS_SUBSYSTEM_SERIALIZATION,
    TURBOJS_SUBSYSTEM_BUILTINS
} QJSInternalSubsystem;

#define TURBOJS_INTERNAL_API static
#define TURBOJS_INTERNAL_INLINE static inline

#endif
