#!/usr/bin/env python3
"""Generate the private TurboJS engine compilation unit from owned domain sources."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = ROOT / "cmake" / "TurboJSSubsystems.json"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        help="output path; defaults to the checked-in path from the subsystem manifest",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    output = args.output or (ROOT / manifest["assembly"]["output"])
    if not output.is_absolute():
        output = ROOT / output

    parts = [
        "/* GENERATED FILE. DO NOT EDIT. */\n",
        "/* Generated by tools/generators/generate_engine_unit.py. */\n",
        "#define TURBOJS_ENGINE_IMPLEMENTATION 1\n",
        '#include "internal/engine_internal.h"\n\n',
    ]
    for subsystem in manifest["dependency_order"]:
        for relative in manifest["subsystems"][subsystem]["sources"]:
            source = ROOT / "src" / relative
            parts.append(f'\n#line 1 "src/{relative}"\n')
            text = source.read_text(encoding="utf-8")
            parts.append(text)
            if not text.endswith("\n"):
                parts.append("\n")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("".join(parts), encoding="utf-8")
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
