#!/usr/bin/env python3
"""Generate the private TurboJS engine compilation unit from owned domain sources."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[2]
manifest = json.loads((root / 'src/subsystems.json').read_text(encoding='utf-8'))
out = root / manifest['assembly']['output']
out.parent.mkdir(parents=True, exist_ok=True)
parts = [
    '/* GENERATED FILE. DO NOT EDIT. */\n',
    '/* Generated by tools/generators/generate_engine_unit.py. */\n',
    '#define TURBOJS_ENGINE_IMPLEMENTATION 1\n',
    '#include "internal/engine_internal.h"\n\n',
]
for subsystem in manifest['dependency_order']:
    for rel in manifest['subsystems'][subsystem]['sources']:
        path = root / 'src' / rel
        parts.append(f'\n#line 1 "src/{rel}"\n')
        parts.append(path.read_text(encoding='utf-8'))
        if not parts[-1].endswith('\n'):
            parts.append('\n')
out.write_text(''.join(parts), encoding='utf-8')
print(out)
